[build-system]
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy",
    "pkgconfig",
    "Cython >=0.29; python_version<'3.8'",
    "Cython >=0.29.14; python_version=='3.8'",
    "Cython >=0.29.15; python_version>='3.9'",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = ["cp37-*", "cp38-*", "cp39-*", "cp310-*", "cp311-*"]
skip = "*-musllinux*"

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
before-all = "yum install -y gcc make zlib-devel openssl-devel libpng-devel"

[tool.cibuildwheel.macos]
archs = ["x86_64"]
before-all = "brew install pkg-config openssl libpng"
before-build = """
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:/opt/homebrew/opt/openssl/lib/pkgconfig"
export C_INCLUDE_PATH="/usr/local/include/libpng:/usr/local/opt/openssl/include:$C_INCLUDE_PATH"
"""
# [tool.cibuildwheel.windows]