# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Install system build dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make zlib1g-dev libssl-dev libpng-dev
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build UCSC kent library
      run: |
        make build-ucsc
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install cython numpy pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and install package
      run: |
          DISTUTILS_DEBUG=1 python -m pip install -v -e .
          ldd -r bbi/cbbi*.so
    - name: Test with pytest
      run: |
        pytest -v
